from typing import Any, Protocol, Self


class Logger(Protocol):
    """Слой application не должен знать про structlog.

    Сигнатуры повторяют structlog, поэтому BoundLogger подходит структурно.
    """

    def bind(self, **kwargs: Any) -> Self: ...
    def debug(self, event: str, **kwargs: Any) -> None: ...
    def info(self, event: str, **kwargs: Any) -> None: ...
    def warning(self, event: str, **kwargs: Any) -> None: ...
    def error(self, event: str, **kwargs: Any) -> None: ...
