from typing import Protocol, Self


class UoW(Protocol):
    """Коммитит на успешном выходе, откатывает на исключении."""

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def flush(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
